name: Build and Release

permissions:
  contents: write
  issues: write
  id-token: write

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Tests
        uses: ./.github/workflows/tests

      - name: Semantic release
        run: npx semantic-release
