name: Build and Release

permissions:
  contents: write
  issues: write

on:
  push:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Tests
        uses: ./.github/workflows/tests

      - name: Semantic release
        run: npx semantic-release
