name: Build and Release

permissions:
  contents: write
  issues: write
  id-token: write

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Tests
        uses: ./.github/workflows/tests

      - name: Semantic release
        run: npx semantic-release
